services:

  a4s-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: backend
    depends_on:
      - postgres


  a4s-webapp:
    build:
      context: ../a4s-webapp
      dockerfile: Dockerfile.dev
    volumes:
      - ../a4s-webapp:/app  # Mount source code for hot reload
      - a4s-webapp-node-modules:/app/node_modules
    ports:
      - "5173:5173"
    container_name: webapp
    depends_on:
      - a4s-backend
    env_file:
      - .env


  a4s-eval:
    build:
      context: ../a4s-eval
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    container_name: eval
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - .env


volumes:
  a4s-webapp-node-modules: