# Generated by Django 6.0.3 on 2026-03-31 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vera_backend', '0004_remove_dataset_plugin_remove_evaluation_dataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('storage_container', models.CharField(choices=[('datasets', 'Datasets'), ('models', 'Models'), ('artifacts', 'Artifacts')], default='datasets', max_length=255)),
                ('evaluation_plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='vera_backend.evaluationplugin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
