# Generated by Django 6.0.3 on 2026-04-16 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vera_backend', '0005_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='package_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugin',
            name='version',
            field=models.CharField(default='latest', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artifact',
            name='evaluation_plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='vera_backend.evaluationplugin'),
        ),
    ]
