# Generated by Django 6.0.3 on 2026-04-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vera_backend', '0005_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationplugin',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evaluationplugin',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationplugin',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationplugin',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Done', 'Done'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='evaluation_plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='vera_backend.evaluationplugin'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Failed', 'Failed'), ('Archived', 'Archived'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Custom', 'Custom')], max_length=255),
        ),
    ]
