# Generated by Django 6.0.3 on 2026-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vera_backend', '0006_plugin_package_name_plugin_version_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plugin',
            unique_together={('name', 'project', 'version', 'package_name')},
        ),
        migrations.AddField(
            model_name='plugin',
            name='display_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
