"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
from corsheaders.defaults import default_headers
from environs import env
from django.core.management.utils import get_random_secret_key

env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
# Default random key only to get the build not to fail
SECRET_KEY = env("DJANGO_SECRET_KEY",default=get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", False)

# Application definition

INSTALLED_APPS = [
     # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.headless',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
    'ninja_jwt',

    # Local
    'a4s_backend'
]

SITE_ID = 1

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
    'ninja.compatibility.files.fix_request_files_middleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": env("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": env("DB_NAME", BASE_DIR / "db.db"),
        "USER": env("DB_USER", ""),
        "PASSWORD": env("DB_PASSWORD", ""),
        "HOST": env("DB_HOST", ""),
        "PORT": env("DB_PORT", ""),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

ALLOWED_HOSTS = ['*']

# Need to add this to make the app work behind a reverse proxy. Without it, even with CRSF and CORS properly configured, django will consider the request unsafe
ENABLE_SSL_PROXY = env.bool("ENABLE_SSL_PROXY", default=False)

if ENABLE_SSL_PROXY:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# --- CORS for your separate frontend(s) ---
# Only for dev
CORS_ALLOW_CREDENTIALS = True
DEFAULT_ALLOWED_ORIGINS = ["http://127.0.0.1:5500", "http://localhost:5173"]
CORS_ALLOWED_ORIGINS = env.list('A4S_BACKEND_CORS_ALLOWED_ORIGINS',DEFAULT_ALLOWED_ORIGINS)
CSRF_TRUSTED_ORIGINS = env.list('A4S_BACKEND_CSRF_TRUSTED_ORIGINS',DEFAULT_ALLOWED_ORIGINS)



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- allauth (headless) ---
ACCOUNT_LOGIN_METHODS =  {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "mandatory"   # must verify before using app

HEADLESS_ONLY = True                       # disable server-rendered pages
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": "/account/verify-email/{key}",
    "account_reset_password": "/account/password/reset",
    "account_signup": "/account/signup",
}
# show OpenAPI spec for headless endpoints (handy in dev)
HEADLESS_SERVE_SPECIFICATION = True
HEADLESS_SPECIFICATION_TEMPLATE_NAME = "headless/spec/swagger_cdn.html"

# custom token strategy class to additionally return JWT on allauth login
HEADLESS_TOKEN_STRATEGY = "config.jwt.SessionAndJWTStrategy"

# Dev email: print verification/reset emails to console
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# --- Ninja JWT ---
NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": 30 * 60,
    "REFRESH_TOKEN_LIFETIME": 7 * 24 * 3600
}


## .env vars

APP_NAME = env("APP_NAME","a4s-backend")
LOG_LEVEL = env("LOG_LEVEL", "INFO")

# S3 settings
# Setting all the defaults as empty - like on database block -, configstatic will run - and consequently also the build
S3_URL = env("S3_URL","")
S3_USER = env("S3_USER","")
S3_PASSWORD = env("S3_PASSWORD","")
S3_DATASETS_BUCKET = env("S3_DATASETS_BUCKET","")
S3_MODELS_BUCKET = env("S3_MODELS_BUCKET","")

# Evaluation module settings
CELERY_BROKER_URL = env("CELERY_BROKER_URL","")
REDIS_BACKEND_URL = env("REDIS_BACKEND_URL","")
CELERY_APP_NAME = env("CELERY_APP_NAME","celery_app")


PLUGIN_PATH = env('PLUGIN_PATH', '')

# --- OIDC / Social Login ---
OIDC_ENABLED = env.bool("OIDC_ENABLED", False)
OIDC_PROVIDER_ID = env("OIDC_PROVIDER_ID", "keycloak")
OIDC_PROVIDER_NAME = env("OIDC_PROVIDER_NAME", "Keycloak")
OIDC_SERVER_URL = env("OIDC_SERVER_URL", "")
OIDC_CLIENT_ID = env("OIDC_CLIENT_ID", "")
OIDC_CLIENT_SECRET = env("OIDC_CLIENT_SECRET", "")
OIDC_TOKEN_AUTH_METHOD = env("OIDC_TOKEN_AUTH_METHOD", "client_secret_post")

# --- allauth socialaccount (OIDC) ---
SOCIALACCOUNT_ADAPTER = "a4s_backend.adapters.OIDCAccountAdapter"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"  # trust IdP's email verification

if OIDC_ENABLED and OIDC_SERVER_URL:
    SOCIALACCOUNT_PROVIDERS = {
        "openid_connect": {
            "APPS": [
                {
                    "provider_id": OIDC_PROVIDER_ID,
                    "name": OIDC_PROVIDER_NAME,
                    "client_id": OIDC_CLIENT_ID,
                    "secret": OIDC_CLIENT_SECRET,
                    "settings": {
                        "server_url": OIDC_SERVER_URL,
                        "token_auth_method": OIDC_TOKEN_AUTH_METHOD,
                    },
                }
            ],
        }
    }
else:
    SOCIALACCOUNT_PROVIDERS = {}