"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
from corsheaders.defaults import default_headers
from environs import env
from django.core.management.utils import get_random_secret_key

env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
# Default random key only to get the build not to fail
SECRET_KEY = env("DJANGO_SECRET_KEY",default=get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", False)

# Application definition

INSTALLED_APPS = [
     # Django core. No accounts, sessions or admin site: people sign in once, at
     # the gateway, and the API reads who they are from its token (KeycloakAuth).
     # contenttypes stays because migration 0004 depends on it.
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # Third party
    'corsheaders',

    # Local
    'aisc_backend'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    # Isolation I7.2: every /api/* call names its project (X-AISC-Project); the
    # door checks the caller may enter it, then opens that project's database.
    'aisc_backend.project_door.ProjectDoor',

    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'ninja.compatibility.files.fix_request_files_middleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Isolation 2026-09-25 (01-specs.md I7.1): every project has its own database,
# `project_<pid without hyphens>`, and the engine's tables live in its schema
# `engine` there. On Postgres the engine therefore has no database of its own:
#
# - `default` is Django's dummy backend, so a query that was not routed to an
#   admitted project fails instead of landing somewhere;
# - `platform` is a raw-SQL connection to the platform database, search_path
#   `core`, read only by the membership check and the project-name lookup;
# - one alias per project database, registered on first use from
#   PROJECT_DATABASE_TEMPLATE by aisc_backend.projectdb, whose router sends every
#   ORM read, write and migration to the alias admitted for the current request.
#
# DB_NAME names only the platform database. On sqlite (a laptop, the unit test
# runner) there is one database, as before: see _single_database() and
# config/settings_single_database.py.
DB_SCHEMA = env("DB_SCHEMA", "")
_db_engine = env("DB_ENGINE", "django.db.backends.sqlite3")
PROJECT_DATABASES = "postgresql" in _db_engine


def _single_database() -> dict:
    """The one database of a laptop or a test run (the layout before isolation).

    A search path is a Postgres idea; the sqlite the test runner builds has no
    schemas and rejects the option outright.
    """
    options = (
        {"options": f"-c search_path={DB_SCHEMA},core"}
        if DB_SCHEMA and "postgresql" in _db_engine
        else {}
    )
    return {
        "ENGINE": _db_engine,
        "NAME": env("DB_NAME", BASE_DIR / "db.db"),
        "USER": env("DB_USER", ""),
        "PASSWORD": env("DB_PASSWORD", ""),
        "HOST": env("DB_HOST", ""),
        "PORT": env("DB_PORT", ""),
        "OPTIONS": options,
    }


if PROJECT_DATABASES:
    DATABASES = {
        "default": {"ENGINE": "django.db.backends.dummy"},
        "platform": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME", "platform"),
            "USER": env("DB_USER", ""),
            "PASSWORD": env("DB_PASSWORD", ""),
            "HOST": env("DB_HOST", ""),
            "PORT": env("DB_PORT", ""),
            "OPTIONS": {"options": "-c search_path=core"},
            "CONN_MAX_AGE": 0,
        },
    }
    # Copied for each project database, with NAME = project_<hex>.
    PROJECT_DATABASE_TEMPLATE = {
        "ENGINE": "django.db.backends.postgresql",
        "USER": env("DB_USER", ""),
        "PASSWORD": env("DB_PASSWORD", ""),
        "HOST": env("DB_HOST", ""),
        "PORT": env("DB_PORT", ""),
        "OPTIONS": {"options": f"-c search_path={DB_SCHEMA or 'engine'}"},
        "CONN_MAX_AGE": 0,
    }
    DATABASE_ROUTERS = ["aisc_backend.projectdb.ProjectDatabaseRouter"]
else:
    DATABASES = {"default": _single_database()}
    PROJECT_DATABASE_TEMPLATE = None
    DATABASE_ROUTERS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

ALLOWED_HOSTS = ['*']

# Need to add this to make the app work behind a reverse proxy. Without it, even with CRSF and CORS properly configured, django will consider the request unsafe
ENABLE_SSL_PROXY = env.bool("ENABLE_SSL_PROXY", default=False)

if ENABLE_SSL_PROXY:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# --- CORS for your separate frontend(s) ---
# Only for dev
CORS_ALLOW_CREDENTIALS = True
DEFAULT_ALLOWED_ORIGINS = ["http://127.0.0.1:5500", "http://localhost:5173"]
CORS_ALLOWED_ORIGINS = env.list('BACKEND_CORS_ALLOWED_ORIGINS',DEFAULT_ALLOWED_ORIGINS)
# Isolation I7.4: the SPA names its project in this header on every call.
CORS_ALLOW_HEADERS = (*default_headers, "x-aisc-project")
CRSF_TRUSTED_ORIGINS = env.list('BACKEND_CRSF_TRUSTED_ORIGINS',DEFAULT_ALLOWED_ORIGINS)



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Keycloak auth (read by aisc_backend.auth.keycloak) ---
# AUTH_ENABLED gates the Keycloak bearer auth; while False the API behaves as before.
AUTH_ENABLED = env.bool("AUTH_ENABLED", default=False)
# The exact issuer string the realm puts in tokens (must match where tokens are obtained from).
KEYCLOAK_ISSUER = env("KEYCLOAK_ISSUER", default="")
# Where the realm publishes its public keys (used to verify token signatures).
KEYCLOAK_JWKS_URL = env("KEYCLOAK_JWKS_URL", default="")

# --- Model listing TLS ---
# Controls TLS certificate verification when listing models from an
# OpenAI-compatible endpoint. Set to "False" to skip verification (allow
# self-signed certificates, e.g. a locally deployed LLM inference server).
# When unset, verification is skipped automatically for private-network hosts.
MODEL_LISTING_SSL_VERIFY = env.bool("MODEL_LISTING_SSL_VERIFY", default=True)

# --- immudb audit ledger (read by aisc_backend.audit.clerk) ---
# Where the immudb server is. Host runs: localhost:3322; inside docker: immudb:3322.
IMMUDB_URL = env("IMMUDB_URL", default="localhost:3322")
IMMUDB_USER = env("IMMUDB_USER", default="immudb")
# Reuse the same dev secret as the container's admin password (one source of truth).
IMMUDB_PASSWORD = env("IMMUDB_PASSWORD", default=env("IMMUDB_ADMIN_PASSWORD", default=""))
# The dedicated audit database (separate from immudb's defaultdb).
IMMUDB_DATABASE = env("IMMUDB_DATABASE", default="auditdb")


## .env vars

APP_NAME = env("APP_NAME","aisc-backend")
LOG_LEVEL = env("LOG_LEVEL", "INFO")

# S3 settings
# Setting all the defaults as empty - like on database block -, configstatic will run - and consequently also the build
S3_URL = env("S3_URL","")
S3_USER = env("S3_USER","")
S3_PASSWORD = env("S3_PASSWORD","")
S3_DATASETS_BUCKET = env("S3_DATASETS_BUCKET","datasets")
S3_MODELS_BUCKET = env("S3_MODELS_BUCKET","models")
S3_ARTIFACTS_BUCKET = env("S3_ARTIFACTS_BUCKET","artifacts")

# Evaluation module settings
CELERY_BROKER_URL = env("CELERY_BROKER_URL","")
REDIS_BACKEND_URL = env("REDIS_BACKEND_URL","")
CELERY_APP_NAME = env("CELERY_APP_NAME","celery_app")


PLUGIN_PATH = env('PLUGIN_PATH', '')
PACKAGE_REGISTRY_URL = env('PACKAGE_REGISTRY_URL', '')
PACKAGE_REGISTRY_USER = env('PACKAGE_REGISTRY_USER', '')
PACKAGE_REGISTRY_PASSWORD = env('PACKAGE_REGISTRY_PASSWORD', '')
PACKAGE_REGISTRY_INDEX = env('PACKAGE_REGISTRY_INDEX', '')