"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
from corsheaders.defaults import default_headers
from environs import env
from django.core.management.utils import get_random_secret_key

from aisc_backend import deployment

empty_str_to_none = lambda v: v if v and v.strip() else None

env.read_env()

_deployment_env = deployment.settings_source(lambda name: env.str(name, default=None))
deployment.check_environment(_deployment_env)
AISC_DEPLOYMENT = deployment.mode(_deployment_env)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
# Default random key only to get the build not to fail
SECRET_KEY = env("DJANGO_SECRET_KEY",default=get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", False)

# Application definition

INSTALLED_APPS = [
     # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # Third party
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.headless',
    'ninja_jwt',

    # Local
    'aisc_backend'
]

SITE_ID = 1

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
    'ninja.compatibility.files.fix_request_files_middleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": env("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": env("DB_NAME", BASE_DIR / "db.db"),
        "USER": env("DB_USER", ""),
        "PASSWORD": env("DB_PASSWORD", ""),
        "HOST": env("DB_HOST", ""),
        "PORT": env("DB_PORT", ""),
    }
}
DATABASE_ROUTERS = []
PROJECT_DATABASE_TEMPLATE = None
# One database per project: the Configurator on Postgres (Ruling 7: read through
# _deployment_env, so a value set in .env counts). Standalone is always one database.
PROJECT_DATABASES = deployment.project_databases(_deployment_env)
DB_SCHEMA = env("DB_SCHEMA", "")


def _single_database() -> dict:
    """The one database of a laptop or a test run (config/settings_single_database.py).

    A search path is a Postgres idea; the sqlite the test runner builds has no
    schemas and rejects the option outright.
    """
    engine = env("DB_ENGINE", "django.db.backends.sqlite3")
    options = (
        {"options": f"-c search_path={DB_SCHEMA},core"}
        if DB_SCHEMA and "postgresql" in engine
        else {}
    )
    return {
        "ENGINE": engine,
        "NAME": env("DB_NAME", BASE_DIR / "db.db"),
        "USER": env("DB_USER", ""),
        "PASSWORD": env("DB_PASSWORD", ""),
        "HOST": env("DB_HOST", ""),
        "PORT": env("DB_PORT", ""),
        "OPTIONS": options,
    }


if AISC_DEPLOYMENT == deployment.CONFIGURATOR:
    # The Configurator owns projects and sign-in: no login of our own (migration
    # 0019 dropped its tables, and Django's accounts, sessions and admin with them,
    # so their apps must not come back and remake them), one database per project
    # behind the door, memberships from the platform.
    _NO_LOGIN_APPS = ("django.contrib.admin", "django.contrib.auth", "django.contrib.sessions",
                      "django.contrib.messages")
    INSTALLED_APPS = [a for a in INSTALLED_APPS
                      if a not in _NO_LOGIN_APPS and not a.startswith(("allauth", "ninja_jwt"))]
    # The door right after CORS, as on the definitive branch (isolation I7.2: every
    # /api/* call names its project in X-AISC-Project).
    MIDDLEWARE = [m for m in MIDDLEWARE
                  if "allauth" not in m and not m.startswith(("django.contrib.sessions.",
                                                               "django.contrib.auth.",
                                                               "django.contrib.messages."))]
    MIDDLEWARE.insert(MIDDLEWARE.index("corsheaders.middleware.CorsMiddleware") + 1,
                      "aisc_backend.project_door.ProjectDoor")
    TEMPLATES[0]["OPTIONS"]["context_processors"] = [
        c for c in TEMPLATES[0]["OPTIONS"]["context_processors"]
        if not c.startswith(("django.contrib.auth.", "django.contrib.messages."))]
    if PROJECT_DATABASES:
        from aisc_backend.projectdb import configurator_databases
        DATABASES, DATABASE_ROUTERS, PROJECT_DATABASE_TEMPLATE = configurator_databases(env)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

ALLOWED_HOSTS = ['*']

# Need to add this to make the app work behind a reverse proxy. Without it, even with CRSF and CORS properly configured, django will consider the request unsafe
ENABLE_SSL_PROXY = env.bool("ENABLE_SSL_PROXY", default=False)

if ENABLE_SSL_PROXY:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# --- CORS for your separate frontend(s) ---
# Only for dev
CORS_ALLOW_CREDENTIALS = True
DEFAULT_ALLOWED_ORIGINS = ["http://127.0.0.1:5500", "http://localhost:5173"]
CORS_ALLOWED_ORIGINS = env.list('BACKEND_CORS_ALLOWED_ORIGINS',DEFAULT_ALLOWED_ORIGINS)
if AISC_DEPLOYMENT == deployment.CONFIGURATOR:
    # Isolation I7.4: the SPA names its project in this header on every call.
    CORS_ALLOW_HEADERS = (*default_headers, "x-aisc-project")
CRSF_TRUSTED_ORIGINS = env.list('BACKEND_CRSF_TRUSTED_ORIGINS',DEFAULT_ALLOWED_ORIGINS)



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- allauth (headless) ---
ACCOUNT_LOGIN_METHODS =  {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "mandatory"   # must verify before using app

HEADLESS_ONLY = True                       # disable server-rendered pages
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": "/account/verify-email/{key}",
    "account_reset_password": "/account/password/reset",
    "account_signup": "/account/signup",
}
# show OpenAPI spec for headless endpoints (handy in dev)
HEADLESS_SERVE_SPECIFICATION = True
HEADLESS_SPECIFICATION_TEMPLATE_NAME = "headless/spec/swagger_cdn.html"

# custom token strategy class to additionally return JWT on allauth login
HEADLESS_TOKEN_STRATEGY = "config.jwt.SessionAndJWTStrategy"

# Dev email: print verification/reset emails to console
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# --- Ninja JWT ---
NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": 30 * 60,
    "REFRESH_TOKEN_LIFETIME": 7 * 24 * 3600
}

# --- Keycloak auth (read by aisc_backend.auth.keycloak) ---
# AUTH_ENABLED gates the Keycloak bearer auth; while False the API behaves as before.
AUTH_ENABLED = env.bool("AUTH_ENABLED", default=False)
# The exact issuer string the realm puts in tokens (must match where tokens are obtained from).
KEYCLOAK_ISSUER = env("KEYCLOAK_ISSUER", default="")
# Where the realm publishes its public keys (used to verify token signatures).
KEYCLOAK_JWKS_URL = env("KEYCLOAK_JWKS_URL", default="")

# --- Model listing TLS ---
# Controls TLS certificate verification when listing models from an
# OpenAI-compatible endpoint. Set to "False" to skip verification (allow
# self-signed certificates, e.g. a locally deployed LLM inference server).
# When unset, verification is skipped automatically for private-network hosts.
MODEL_LISTING_SSL_VERIFY = env.bool("MODEL_LISTING_SSL_VERIFY", default=True)

# --- immudb audit ledger (read by aisc_backend.audit.clerk) ---
# Where the immudb server is. Host runs: localhost:3322; inside docker: immudb:3322.
IMMUDB_URL = env("IMMUDB_URL", default="localhost:3322")
IMMUDB_USER = env("IMMUDB_USER", default="immudb")
# Reuse the same dev secret as the container's admin password (one source of truth).
IMMUDB_PASSWORD = env("IMMUDB_PASSWORD", default=env("IMMUDB_ADMIN_PASSWORD", default=""))
# The dedicated audit database (separate from immudb's defaultdb).
IMMUDB_DATABASE = env("IMMUDB_DATABASE", default="auditdb")


## .env vars

APP_NAME = env("APP_NAME","aisc-backend")
LOG_LEVEL = env("LOG_LEVEL", "INFO")

# S3 settings
# Setting all the defaults as empty - like on database block -, configstatic will run - and consequently also the build
S3_URL = env("S3_URL","")
S3_USER = env("S3_USER","")
S3_PASSWORD = env("S3_PASSWORD","")
S3_DATASETS_BUCKET = env("S3_DATASETS_BUCKET","datasets")
S3_MODELS_BUCKET = env("S3_MODELS_BUCKET","models")
S3_ARTIFACTS_BUCKET = env("S3_ARTIFACTS_BUCKET","artifacts")

# Evaluation module settings
CELERY_BROKER_URL = env("CELERY_BROKER_URL","")
REDIS_BACKEND_URL = env("REDIS_BACKEND_URL","")
CELERY_APP_NAME = env("CELERY_APP_NAME","celery_app")


PLUGIN_PATH = env('PLUGIN_PATH', '')
PACKAGE_REGISTRY_URL = env('PACKAGE_REGISTRY_URL', '')
PACKAGE_REGISTRY_USER = empty_str_to_none(env('PACKAGE_REGISTRY_USER', None))
PACKAGE_REGISTRY_PASSWORD = empty_str_to_none(env('PACKAGE_REGISTRY_PASSWORD', None))
PACKAGE_REGISTRY_INDEX = env('PACKAGE_REGISTRY_INDEX', '')