# Generated by Django 5.2.7 on 2025-10-14 14:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual'), ('Requested', 'Requested'), ('Failed', 'Failed'), ('Done', 'Done'), ('Awaiting_data', 'Awaiting_data')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('datashape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='a4s_backend.datashape')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('feature_type', models.CharField(choices=[('Date', 'Date'), ('Categorical', 'Categorical'), ('Integer', 'Integer'), ('Float', 'Float')], max_length=255)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('datashape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='a4s_backend.datashape')),
            ],
        ),
        migrations.AddField(
            model_name='datashape',
            name='date_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_feature', to='a4s_backend.feature'),
        ),
        migrations.AddField(
            model_name='datashape',
            name='target_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_feature', to='a4s_backend.feature'),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('model_hub', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=True)),
                ('data', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='a4s_backend.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Closed', 'Closed'), ('Pending', 'Pending'), ('Archived', 'Archived'), ('Created', 'Created')], max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('window_size', models.CharField(max_length=255)),
                ('datashape', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='a4s_backend.datashape')),
            ],
        ),
    ]
