# Generated by Django 5.2.7 on 2025-10-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4s_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='error',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='uncertainty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='unit',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
