# Generated by Django 5.2.7 on 2026-01-09 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('type_spec', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('config', models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual'), ('Requested', 'Requested'), ('Failed', 'Failed'), ('Done', 'Done'), ('Awaiting_data', 'Awaiting_data')], max_length=255)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='datashape', to='aisc_backend.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Direct',
            fields=[
                ('metric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aisc_backend.metric')),
            ],
            options={
                'abstract': False,
            },
            bases=('aisc_backend.metric',),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('feature_type', models.CharField(choices=[('Date', 'Date'), ('Categorical', 'Categorical'), ('Integer', 'Integer'), ('Float', 'Float')], max_length=255)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('datashape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='aisc_backend.datashape')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datashape',
            name='date_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_feature', to='aisc_backend.feature'),
        ),
        migrations.AddField(
            model_name='datashape',
            name='target_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_feature', to='aisc_backend.feature'),
        ),
        migrations.CreateModel(
            name='MetricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('metrics', models.ManyToManyField(related_name='categories', to='aisc_backend.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('model_hub', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='aisc_backend.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Archived', 'Archived'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Custom', 'Custom')], max_length=255)),
                ('task', models.UUIDField(blank=True, default=None, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='aisc_backend.dataset')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='aisc_backend.model')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('observer', models.CharField(max_length=255)),
                ('tool', models.CharField(max_length=255)),
                ('whenObserved', models.DateTimeField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='aisc_backend.evaluation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(default='N/A', max_length=255)),
                ('time', models.DateTimeField()),
                ('score', models.FloatField()),
                ('error', models.CharField(default='N/A', max_length=255)),
                ('uncertainty', models.FloatField(default=0)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='aisc_backend.feature')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='aisc_backend.metric')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='aisc_backend.observation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_plugins', to='aisc_backend.dataset')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_plugins', to='aisc_backend.evaluation')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_plugins', to='aisc_backend.model')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_plugins', to='aisc_backend.plugin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='plugin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='aisc_backend.plugin'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Closed', 'Closed'), ('Pending', 'Pending'), ('Archived', 'Archived'), ('Created', 'Created')], max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('window_size', models.CharField(max_length=255)),
                ('expected_datashape', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='aisc_backend.datashape')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plugin',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_plugins', to='aisc_backend.project'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='aisc_backend.project'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='aisc_backend.project'),
        ),
        migrations.CreateModel(
            name='Derived',
            fields=[
                ('metric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aisc_backend.metric')),
                ('expression', models.CharField(max_length=255)),
                ('base_metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derived_by', to='aisc_backend.metric')),
            ],
            options={
                'abstract': False,
            },
            bases=('aisc_backend.metric',),
        ),
        migrations.AlterUniqueTogether(
            name='plugin',
            unique_together={('name', 'project')},
        ),
    ]
