# Generated by Django 6.0.3 on 2026-04-16 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisc_backend', '0005_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='package_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugin',
            name='version',
            field=models.CharField(default='latest', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artifact',
            name='evaluation_plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='aisc_backend.evaluationplugin'),
        ),
        migrations.AddField(
            model_name='evaluationplugin',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evaluationplugin',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationplugin',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationplugin',
            name='status',
            field=models.CharField(
                choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Done', 'Done'), ('Failed', 'Failed')],
                default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='status',
            field=models.CharField(
                choices=[('Done', 'Done'), ('Failed', 'Failed'), ('Archived', 'Archived'), ('Pending', 'Pending'),
                         ('Processing', 'Processing'), ('Custom', 'Custom')], max_length=255),
        ),
    ]
