# Generated by Django 6.0.4 on 2026-05-06 09:54

import aisc_backend.models.measure
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisc_backend', '0008_remove_datashape_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[aisc_backend.models.measure.validate_flat_json]),
        ),
    ]
