# Generated by Django 6.0.4 on 2026-05-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisc__backend', '0009_alter_measurement_dimensions'),
    ]

    # The `enabled` column was historically added by an orphaned 0008
    # migration on some environments (the original soft-disable patch).
    # Use IF NOT EXISTS so a fresh DB and a previously-patched DB both
    # converge to the same end state without manual intervention.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='plugin',
                    name='enabled',
                    field=models.BooleanField(default=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE aisc_backend_plugin ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;",
                    reverse_sql="ALTER TABLE aisc_backend_plugin DROP COLUMN IF EXISTS enabled;",
                ),
            ],
        ),
    ]
