# Generated by Django 6.0.6 on 2026-08-03 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisc_backend', '0012_measurement_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('api_key', 'API Key'), ('datashape', 'DataShape / Feature Definition'), ('general', 'General Setting')], max_length=50)),
                ('key', models.CharField(max_length=255)),
                ('service_type', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_value', models.TextField(blank=True, default='')),
                ('masked_value', models.CharField(blank=True, default='', max_length=255)),
                ('json_value', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='aisc_backend.project')),
            ],
        ),
        migrations.AddField(
            model_name='evaluationplugin',
            name='datashape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_plugins', to='aisc_backend.projectsetting'),
        ),
        migrations.AddConstraint(
            model_name='projectsetting',
            constraint=models.UniqueConstraint(fields=('project', 'category', 'key'), name='unique_project_setting_key'),
        ),
    ]
