# Generated by Django 6.0.6 on 2026-08-05 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisc_backend', '0012_measurement_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('secrets', 'Secrets'), ('datashape', 'DataShape / Feature Definition'), ('general', 'General Setting')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_value', models.TextField(blank=True, default='')),
                ('masked_value', models.CharField(blank=True, default='', max_length=255)),
                ('json_value', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='aisc_backend.project')),
            ],
        ),
        migrations.CreateModel(
            name='PluginConfigSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plugin_setting_key', models.CharField(max_length=255)),
                ('plugin_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_mappings', to='aisc_backend.pluginconfig')),
                ('project_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_mappings', to='aisc_backend.projectsetting')),
            ],
        ),
        migrations.AddField(
            model_name='pluginconfig',
            name='project_settings',
            field=models.ManyToManyField(blank=True, related_name='plugin_configs', through='aisc_backend.PluginConfigSetting', to='aisc_backend.projectsetting'),
        ),
        migrations.AddConstraint(
            model_name='projectsetting',
            constraint=models.UniqueConstraint(fields=('project', 'category', 'key'), name='unique_project_setting_key'),
        ),
        migrations.AddConstraint(
            model_name='pluginconfigsetting',
            constraint=models.UniqueConstraint(fields=('plugin_config', 'plugin_setting_key'), name='unique_plugin_config_setting_key'),
        ),
    ]
