# Generated by Django 6.0.6 on 2026-09-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisc_backend', '0013_projectsetting_pluginconfigsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='catalogue_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
