# Generated by Django 6.0.6 on 2026-09-08 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisc_backend', '0014_aicomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicomponent',
            name='endpoint_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='aicomponent',
            name='json_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aicomponent',
            name='secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='aisc_backend.projectsetting'),
        ),
        migrations.AddField(
            model_name='aicomponent',
            name='source_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_datashapes', to='aisc_backend.aicomponent'),
        ),
        migrations.AlterField(
            model_name='aicomponent',
            name='component_type',
            field=models.CharField(choices=[('dataset', 'Dataset'), ('model', 'Model / file-backed artifact'), ('llm', 'LLM (OpenAI-compatible)'), ('rest', 'REST endpoint'), ('datashape', 'DataShape (derived from a dataset)')], default='model', max_length=50),
        ),
    ]
