# Generated by Django 6.0.6 on 2026-09-22 16:54

"""the project link is named project_id

Every module names the platform project its rows belong to, and each named it
differently. One name in the database, `project_id`; the model attribute stays
`platform_project_id`, because inside the engine `project` already means the
engine's own project.

Django turns this into a column rename, so the data stays where it is.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisc_backend', '0016_one_project_per_platform_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='platform_project_id',
            field=models.UUIDField(blank=True, db_column='project_id', db_index=True, null=True),
        ),
    ]
