# Generated by Django 6.0.6 on 2026-09-09 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisc_backend', '0016_rename_projectsetting_to_projectconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfig',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='aisc_backend.project'),
        ),
    ]
