# Generated by Django 6.0.6 on 2026-09-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aisc_backend', '0018_alter_artifact_table_alter_dataset_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='derived',
            table='derived',
        ),
        migrations.AlterModelTable(
            name='direct',
            table='direct',
        ),
    ]
