# Generated by Django 6.0.6 on 2026-09-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aisc_backend', '0020_alter_derived_table_alter_direct_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aicomponent',
            table='ai_component',
        ),
        migrations.AlterModelTable(
            name='aisystem',
            table='ai_system',
        ),
        migrations.AlterModelTable(
            name='evaluationinput',
            table='evaluation_input',
        ),
        migrations.AlterModelTable(
            name='pluginconfigprojectconfig',
            table='plugin_config_project_config',
        ),
        migrations.AlterModelTable(
            name='projectconfig',
            table='project_config',
        ),
    ]
